### PR TITLE
enable mypy and add type hints to __init__.py

### PR DESCRIPTION
**Pull request by gruebel**
- enabled mypy
- added type hints to __init__.py to make reviewing easier and more gradual
- moved linting and type checking to a dedicated CI job

Relates #99

### CODE REVIEW

**Review by jkowalleck — APPROVED** [review]

**Comment by gruebel** [comment]
@pombredanne would be great to get a review for this PR 🙂

**Comment by gruebel** [comment]
hey @pombredanne sorry to bother you, do you have time to review my PR?

**Comment by gruebel** [comment]
hey @pombredanne sorry to bother you, any interest in my PR?

**Review by pombredanne — APPROVED** [review]
Thanks! LGTM. I am merging this in #111

**Pull request merged**
